# Site settings
title: Sam Stewart 
email: sams@umn.edu 
description: > # this means to ignore newlines until "baseurl:"
  Academic blog for PhD math graduate student Sam Stewart.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samstewart.github.io" # the base hostname & protocol for your site
twitter_username: BreakingNews
github_username:  samstewart

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "Sam Stewart"
google_analytics: "UA-84857382-1"
google_site_verification: "d3M1XYWvcVN0_zd_g_7zxNy1hXouEDS6xdYx1FfC4ro"
# bing_webmastertools_id: ""
